.TH WS-SESSION 1 "April 12, 2015" "ws-session 1.0"
.OS Linux
.SH NAME
ws-session - a session manager for virtual desktops
.SH SYNOPSIS
.B ws-session
.RB [\| \-h \||\| \-l \||\| \-m \||\| \-p \||\| \-v\| ]
.br
.B ws-session
.RB [\| \-c \||\| \-o \ [ \-f \|]| \-r ]
.IR sessionname
.br
.B ws-session
.RB \| \-a
.IR system_action \|

.SH DESCRIPTION
.B ws-session
creates one session for every 
.IR virtual-desktop ,
.I workspace
or
.IR tag \.

You can start and stop sessions independent of each other.

You can configure what should be part of your sessions: browser history/tabs,
bash history, terminals with cwd, editors and open files, open pdfs, ncurses
applications like mutt, htop, ssh (tmux attach) and everything else you can
think of and write a wrapper.

You must use one option at a time:
.SS OPTIONS
.TP
\fB\-a\fP, \fBall \fIsystem_action
.br
Close all sessions and then run a 
.IR system_action .
You can create new 
.I system_actions
in your rc file.
.TP
\fB\-c\fP, \fBclose\fP [\fIsessionname\fP]
.br
Close current session if no session name is supplied.
Or close the session named 
.IR sessionname \.
.TP
\fB\-h\fP, \fBhelp
.br
Print the help.
.TP
\fB\-l\fP, \fBlist
.br
List all saved sessions in 
.IR $S_DATA_FOLDER \.
.TP
\fB\-m\fP, \fBmenu
.br
Start a session from a menu.
You have to set 
.I $S_MENU
in the rc file.
.TP
\fB\-o\fP, \fBopen\fP [\fB-f\fP] \fIsessionname
.br
Start the session with name 
.IR sessionname \.
.br
Use
.B -f
to open a session on an already open tag with the same name.
.TP
\fB\-p\fP, \fBpath
.br
Prints the temporary path of the current session. Can be used for dotfiles etc.
.TP
\fB\-r\fP, \fBrestore \fIsessionname
.br
Restore the session named 
.I sessionname
to a previous state.
You can do it up to 
.I $S_NUMBER_OF_BACKUPS
times.
.TP
\fB\-v\fP, \fBversion
Print version
.SS DEBUG OPTIONS
.TP
.BI debug \ functionname
Executes the function named 
.I functionname
or any command, after sourcing
everything.
.br
WARNING: don't try
.B ws-session debug rm -rf *
.br
EXAMPLE:
.B ws-session debug s_list_app_seltag
.br
.TP
\fBprint\fP [\fIvariable\fP]
Prints the content of the variables supplied.
.br
EXAMPLE:
.B ws-session print S_LIB_FOLDER S_SEL_TAG
.br
.SH FILES
.TP
.B /etc/xdg/ws-session/ws-session.rc
The default configuration file, all possible configuration items are described
in this file.
Copy it to
.I $HOME/.ws-session.rc
or
.IR $XDG_CONFIG_HOME/ws-session/ws-session.rc \.
.TP
.B /etc/xdg/ws-session/bin/*
Here are the default application wrappers, copy or link them to your path.
.TP
.B /usr/lib/ws-session/app
Here are the application functions located. You can create the folder 
.IR $S_CONFIG_FOLDER/app ,
there you can put your own versions of your application functions.
.TP
.B /usr/lib/ws-session/wm
Here are the windowmanager functions located. You can create the folder
.IR $S_CONFIG_FOLDER/wm ,
there you can put your own versions of your windowmanager functions.
.SH SEE ALSO
.I ws-session(7)
.SH BUGS
Please report bugs at 
.IR <http://github.com/ctx/ws-session/issues> .
.SH AUTHOR
Ciril Troxler (ctroxler@gmail.com)
.SH COPYRIGHT
License GPLv3+: GNU GPL version 3 or later 
.IR <http://gnu.org/licenses/gpl.html>
 
This is free software; you are free to change and redistribute it.
